java:
	# make this complete first and when it works
	# parallelize it and modify the makefile!
	javac sequential.java
	time sh check-solution.sh java Preflow
	@echo PASS all tests

para:
	# make this complete first and when it works
	# parallelize it and modify the makefile!
	javac concurrent.java
	time sh check-solution.sh java Preflow
	@echo PASS all tests
